### ISSUE TITLE
feat: retry mechanism

### ISSUE THREAD

**Issue by gzur** [juliangruber/merge-pull-request-action#18]
### Description
I'm relying on the `matrix` functionality to generate jobs that create (and sometimes) auto-merge PR's.

Sometimes, a run will fail with the 
```
Error: Base branch was modified. Review and try the merge again.
```

Basically, it appears that the Github API is not keeping up with my furious merging, but I'm wondering whether it would make sense to implement a simple (probably optional) retry-mechanism.

### Workaround:

Just to be clear, this is not a blocker, the issue can be eliminated by [disabling parallelism](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymax-parallel) (`strategy.max-parallel: 1`) on the workflow side. 

Sequential execution just makes me sad :)

**Comment by juliangruber** [comment]
Hey, maybe https://github.com/marketplace/actions/retry-step could work for your use case?

> Sequential execution just makes me sad :)

💯

**Comment by gzur** [comment]
I ended up doing something like that. Feel free to close this PR.
