### ISSUE TITLE
Node v20

### ISSUE THREAD

**Issue by marians** [juliangruber/merge-pull-request-action#31]
It would be nice to have a new version available that is compatible with Node v20. Workflow runs of the latest release already issue warnings regarding Node v16 being phased out.

See https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by juliangruber** [comment]
Pull requests welcome 🙏

**Comment by revrenlove** [comment]
@marians 

Specifying the latest version worked for me:

`uses: juliangruber/merge-pull-request-action@v1.3.1`
