### ISSUE TITLE
Error: Not Found

### ISSUE THREAD

**Issue by MattHoldgate** [juliangruber/merge-pull-request-action#32]
Error: Not Found

Im receiving a Error: Not Found message in my build.

![image](https://github.com/juliangruber/merge-pull-request-action/assets/83656370/68ccad83-dfd6-4266-ae2e-54c12bc4e94c)

No idea what it's not found because the PR is there

**Comment by juliangruber** [comment]
`repo: juliangruber/octokit-action`: You're trying to merge a pull request on my repo. You should use yours instead.
